// Generated by gencpp from file demo1/add.msg
// DO NOT EDIT!


#ifndef DEMO1_MESSAGE_ADD_H
#define DEMO1_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <demo1/addRequest.h>
#include <demo1/addResponse.h>


namespace demo1
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace demo1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo1::add > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::demo1::add&) { return value(); }
};

template<>
struct DataType< ::demo1::add > {
  static const char* value()
  {
    return "demo1/add";
  }

  static const char* value(const ::demo1::add&) { return value(); }
};


// service_traits::MD5Sum< ::demo1::addRequest> should match
// service_traits::MD5Sum< ::demo1::add >
template<>
struct MD5Sum< ::demo1::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo1::add >::value();
  }
  static const char* value(const ::demo1::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo1::addRequest> should match
// service_traits::DataType< ::demo1::add >
template<>
struct DataType< ::demo1::addRequest>
{
  static const char* value()
  {
    return DataType< ::demo1::add >::value();
  }
  static const char* value(const ::demo1::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo1::addResponse> should match
// service_traits::MD5Sum< ::demo1::add >
template<>
struct MD5Sum< ::demo1::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo1::add >::value();
  }
  static const char* value(const ::demo1::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo1::addResponse> should match
// service_traits::DataType< ::demo1::add >
template<>
struct DataType< ::demo1::addResponse>
{
  static const char* value()
  {
    return DataType< ::demo1::add >::value();
  }
  static const char* value(const ::demo1::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO1_MESSAGE_ADD_H
